name = "novel-site"
pages_build_output_dir = "."
compatibility_date = "2026-02-01"

[[d1_databases]]
binding = "DB"
database_name = "novel-db"
database_id = "c3791335-7790-4144-b9b7-4fe17d561067"

[[r2_buckets]]
binding = "R2"
bucket_name = "novel-storage"
